[package]
name = "eclipse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = "0.4.0"
clap = "2.33.1"
ed25519-dalek = "=1.0.1"
serde_json = "1.0.56"
solana-client = "1.8.3"
solana-vote-program = "1.8.3"
solana-sdk = "1.8.3"
solana-transaction-status = "1.8.3"
ticker = "0.1.1"
url = "2.2.2"
